
#language: android


before_install:
    - chmod +x gradlew

install:
 - chmod +x gradlew
 - wget --no-check-certificate https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
 - unzip sdk-tools-linux-3859397.zip
 - yes | tools/bin/sdkmanager --licenses
  
script:
  - echo sdk.dir=$PWD > local.properties 
  - ./gradlew assemble
